// solid-test/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';

import './index.css';
import App from './App';
import w from "./test";
// eslint-disable-next-line @typescript-eslint/no-unused-expressions
w && true;

const root = document.getElementById('root');

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?',
  );
}

render(() => <App title="Hello!" />, root!);

// react-test/src/index.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import w from "./test";
// eslint-disable-next-line @typescript-eslint/no-unused-expressions
w && true;

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App title="Hello!"/>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
